// Generated by CoffeeScript 1.7.1
(function() {
  this.on_ready = function(func) {
    return $(document).ready(function() {
      return func.call(window);
    });
  };

  this.on_ready(function() {
    return $('.title').css('opacity', 1);
  });

}).call(this);
